<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="4" time="0.126" timestamp="2023-06-07T20:21:29.844594" hostname="KBP1-LHP-A10598"><testcase classname="test_oop.TestSimple" name="test_human_fixture" time="0.002"><failure message="assert 23 == 25&#10; +  where 23 = &lt;Lesson_15.tests.example_user.Human object at 0x0000022F78663210&gt;.age">self = &lt;Lesson_16.tests.test_oop.TestSimple object at 0x0000022F785DB810&gt;, human = &lt;Lesson_15.tests.example_user.Human object at 0x0000022F78663210&gt;

    @pytest.mark.fast
    @pytest.mark.regression
    def test_human_fixture(self, human):
        human.grow()
&gt;       assert human.age == 25
E       assert 23 == 25
E        +  where 23 = &lt;Lesson_15.tests.example_user.Human object at 0x0000022F78663210&gt;.age

test_oop.py:10: AssertionError</failure></testcase><testcase classname="test_oop.TestSimple" name="test_db_fixture_name" time="0.004" /><testcase classname="test_oop.TestSimple" name="test_db_fixture_age" time="0.002"><failure message="AssertionError: assert 15 == 11&#10; +  where 15 = &lt;built-in method get of dict object at 0x0000022F788EB3C0&gt;('age')&#10; +    where &lt;built-in method get of dict object at 0x0000022F788EB3C0&gt; = {'age': 15, 'name': 'Marta'}.get">self = &lt;Lesson_16.tests.test_oop.TestSimple object at 0x0000022F788EB750&gt;, db = {'age': 15, 'name': 'Marta'}

    @pytest.mark.regression
    def test_db_fixture_age(self, db):
&gt;       assert db.get('age') == 11
E       AssertionError: assert 15 == 11
E        +  where 15 = &lt;built-in method get of dict object at 0x0000022F788EB3C0&gt;('age')
E        +    where &lt;built-in method get of dict object at 0x0000022F788EB3C0&gt; = {'age': 15, 'name': 'Marta'}.get

test_oop.py:17: AssertionError</failure></testcase><testcase classname="test_oop.TestSimple" name="test_db_fixture_fail" time="0.002" /></testsuite></testsuites>